# Generated by Django 4.2.1 on 2024-03-06 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("credits", models.CharField(max_length=100)),
                ("prerequisites", models.CharField(max_length=100, null=True)),
                ("type", models.CharField(max_length=100)),
                ("college", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("semester", models.CharField(max_length=100)),
                ("year_level", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        default="img/placeholder.png", null=True, upload_to="img/"
                    ),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("middleName", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=100)),
                ("birthday", models.DateField()),
                ("address", models.CharField(max_length=100)),
                ("college", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=100)),
                ("college", models.CharField(max_length=100)),
                ("room_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_section", models.CharField(max_length=100)),
                ("section_college", models.CharField(max_length=100)),
                ("number_students", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="InstructorCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="class_sched.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="class_sched.instructor",
                    ),
                ),
                (
                    "sections",
                    models.ManyToManyField(blank=True, to="class_sched.section"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="instructor",
            name="course_handled",
            field=models.ManyToManyField(
                through="class_sched.InstructorCourse", to="class_sched.course"
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="section_handled",
            field=models.ManyToManyField(blank=True, to="class_sched.section"),
        ),
        migrations.AddField(
            model_name="instructor",
            name="user_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="class_sched.instructor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.CharField(max_length=100)),
                ("end_time", models.CharField(max_length=100)),
                ("semester", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="class_sched.course",
                    ),
                ),
                ("days_of_week", models.ManyToManyField(to="class_sched.week")),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="class_sched.instructor",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="class_sched.room",
                    ),
                ),
            ],
        ),
    ]
