# Generated by Django 4.2.1 on 2024-03-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='section_handled',
        ),
        migrations.AddField(
            model_name='instructor',
            name='section_handled',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
