# Generated by Django 4.2.1 on 2024-03-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='section_handled',
        ),
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='section_major_course',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='course_handled',
            field=models.ManyToManyField(blank=True, through='class_sched.InstructorCourse', to='class_sched.course'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
