# Generated by Django 4.2.1 on 2024-03-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0002_remove_instructor_section_handled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='section_handled',
        ),
    ]
