# Generated by Django 4.2.1 on 2024-03-13 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0002_remove_instructor_section_handled_course_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorcourse',
            name='sections',
        ),
        migrations.AddField(
            model_name='instructorcourse',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='class_sched.section'),
            preserve_default=False,
        ),
    ]
