# Generated by Django 4.2.1 on 2024-03-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0003_remove_instructor_section_handled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='course_handled',
            field=models.ManyToManyField(blank=True, through='class_sched.InstructorCourse', to='class_sched.course'),
        ),
    ]
