# Generated by Django 4.2.1 on 2024-02-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
