# Generated by Django 4.2.1 on 2024-03-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0003_remove_instructorcourse_sections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='days_of_week',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
