# Generated by Django 4.2.1 on 2024-02-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0004_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('suffix', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('time_availability', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
