# Generated by Django 4.2.1 on 2024-03-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0004_remove_classschedule_days_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.IntegerField(),
        ),
    ]
