# Generated by Django 4.2.1 on 2024-03-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0004_alter_instructor_course_handled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
