# Generated by Django 4.2.1 on 2024-03-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0005_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
