# Generated by Django 4.2.1 on 2024-02-06 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_sched', '0006_instructor_profile_pic_instructor_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='instructor',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
