# Generated by Django 4.2.1 on 2024-03-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0006_course_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_status',
        ),
    ]
