# Generated by Django 4.2.1 on 2024-03-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0006_alter_classschedule_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
