# Generated by Django 4.2.1 on 2024-03-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0007_remove_course_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
