# Generated by Django 4.2.1 on 2024-02-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0007_remove_instructor_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='user_profile',
        ),
    ]
