# Generated by Django 4.2.1 on 2024-03-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0007_alter_classschedule_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='semester',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
