# Generated by Django 4.2.1 on 2024-03-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0008_course_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_major_course',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
