# Generated by Django 4.2.1 on 2024-02-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0009_classschedule_course_credits_course_prerequisites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
