# Generated by Django 4.2.1 on 2024-02-07 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0011_imageupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
