# Generated by Django 4.2.1 on 2024-02-07 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0012_delete_imageupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='profile_pic',
        ),
    ]
