# Generated by Django 4.2.1 on 2024-02-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0013_remove_instructor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=100),
        ),
    ]
