# Generated by Django 4.2.1 on 2024-02-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0014_alter_instructor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
