# Generated by Django 4.2.1 on 2024-02-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0015_alter_instructor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
