# Generated by Django 4.2.1 on 2024-02-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0017_alter_instructor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
