# Generated by Django 4.2.1 on 2024-02-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0018_instructor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_picture',
            field=models.ImageField(default='img/placeholder.png', null=True, upload_to='img/'),
        ),
    ]
