# Generated by Django 4.2.1 on 2024-02-17 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0019_alter_instructor_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='suffix',
            new_name='middleName',
        ),
    ]
