# Generated by Django 4.2.1 on 2024-02-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0020_rename_suffix_instructor_middlename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorSchedule',
        ),
    ]
