# Generated by Django 4.2.1 on 2024-02-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0021_delete_instructorschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='year',
            field=models.TextField(),
        ),
    ]
