# Generated by Django 4.2.1 on 2024-02-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0023_alter_classschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='college',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
