# Generated by Django 4.2.1 on 2024-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0024_course_college_alter_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='year_level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
