# Generated by Django 4.2.1 on 2024-02-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0025_course_semester_course_year_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='time_availability',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='department',
            new_name='college',
        ),
    ]
