# Generated by Django 4.2.1 on 2024-02-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0026_rename_time_availability_instructor_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='department',
            new_name='college',
        ),
    ]
