# Generated by Django 4.2.1 on 2024-02-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0027_rename_department_instructor_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
