# Generated by Django 4.2.1 on 2024-02-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0029_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
