# Generated by Django 4.2.1 on 2024-02-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0030_room_room_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conflict',
        ),
    ]
