# Generated by Django 4.2.1 on 2024-03-01 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0031_delete_conflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='class_sched.course'),
        ),
    ]
