# Generated by Django 4.2.1 on 2024-03-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0032_alter_classschedule_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='course_handled',
            field=models.ManyToManyField(to='class_sched.course'),
        ),
    ]
