# Generated by Django 4.2.1 on 2024-03-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0033_instructor_course_handled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='days_of_week',
            field=models.ManyToManyField(to='class_sched.week'),
        ),
    ]
