# Generated by Django 4.2.1 on 2024-03-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0035_section_classschedule_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='yr_level',
            field=models.IntegerField(max_length=100),
        ),
    ]
