# Generated by Django 4.2.1 on 2024-03-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0037_section_section_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='section_handled',
            field=models.ManyToManyField(blank=True, to='class_sched.section'),
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='section',
        ),
        migrations.AlterField(
            model_name='section',
            name='yr_level',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='section',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
