# Generated by Django 4.2.1 on 2024-03-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0038_instructor_section_handled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='program',
            new_name='program_section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='yr_level',
        ),
    ]
