# Generated by Django 4.2.1 on 2024-03-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sched', '0039_rename_program_section_program_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='number_students',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
